### ISSUE TITLE
Index creation failed

### ISSUE THREAD

**Issue by mzehrer** [toshi-search/Toshi#103]
Index creation (schema from README) fails, the cli output is:

INFO  toshi::index > Indexes: []

  ______         __   _   ____                 __
 /_  __/__  ___ / /  (_) / __/__ ___ _________/ /
  / / / _ \(_-</ _ \/ / _\ \/ -_) _ `/ __/ __/ _ \
 /_/  \___/___/_//_/_/ /___/\__/\_,_/_/  \__/_//_/
 Such Relevance, Much Index, Many Search, Wow

 INFO  toshi        > "GET / HTTP/1.1" 200 15.365µs
 INFO  toshi::router > Error { kind: "ErrorKind::Internal" }
 INFO  toshi         > "PUT /test_index HTTP/1.1" 500 56.23µs

No files are created in the data directory.

**Comment by hntd187** [comment]
The docs have a pending PR to update them the request should be `/test_index/_create`
