### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by fulmicoton** [toshi-search/Toshi#12]
It would be great to be able to 

```bash
cargo install toshi
```

**Comment by hntd187** [comment]
Done and done :-) this does show though I need to finally add some command line args to make the binary stand better on it's own.

https://crates.io/crates/toshi

**Comment by fulmicoton** [comment]
Awesome, thanks!

**Comment by kristiandupont** [comment]
It looks like this crate is not up to date. Is this not supported any more?

**Comment by hntd187** [comment]
I can push one at anytime it's just no one has asked for it.
