### ISSUE TITLE
How do I search the documents?

### ISSUE THREAD

**Issue by ezcamlive** [toshi-search/Toshi#153]

**Comment by hntd187** [comment]
Please read the documentation

**Comment by Krizz** [comment]
The documentation, as far as I can tell currently only defines the API endpoints and not the query format itself. Seems like the best way to get up and running is taking a look at the test cases for now https://github.com/toshi-search/Toshi/blob/5a370989c4a4c274028a6078e0adea1948f43e25/src/handlers/search.rs#L165

**Comment by hntd187** [comment]
@Krizz the documentation needs an entire re-over, I'm trying to get clustering in an experimental state so I can rewrite lots of docs to have the clustering aspects included. But the test cases are a good place to get started

**Comment by ezcamlive** [comment]
Thanks Krizz
