### ISSUE TITLE
Additions to .gitignore

### ISSUE THREAD

**Issue by fhaynes** [toshi-search/Toshi#17]
A `cargo build` seems to leave these directories lying around:
```
logs/
new_index/
```
Should we clean them up? Or add them to .gitignore?

**Comment by fhaynes** [comment]
@hntd187 is it cleaning these up now?

**Comment by hntd187** [comment]
remember we has spoke about this that there was that annoying windows bug with deleting directories? that rust apparently has to run the remove_dir twice on windows
