### ISSUE TITLE
Add option for consul server address

### ISSUE THREAD

**Issue by fhaynes** [toshi-search/Toshi#18]
Toshi should accept a Consul address as a CLI flag. Related to #15

**Comment by hntd187** [comment]
In addition I think there should be an issue for discussion about what stuff we wanna store in consul for cluster coordination.

**Comment by fhaynes** [comment]
Yup! Off the top of my head:

- IP
- Hostname
- Current CPU load (5 min avg or something)
- Free desk space
- iowait
- Node role if we use roles
- Free RAM

**Comment by fhaynes** [comment]
Done.
