### ISSUE TITLE
Consul organization and keys

### ISSUE THREAD

**Issue by hntd187** [toshi-search/Toshi#19]
So using consul's kv store we can do more in terms of orchestration than just leader election (if we even want to go that route)

but basically
`/service/toshi/leader true` 

whichever node gets the session lock on this is the leader then nodes can join the cluster and announce their address perhaps via something like

`/service/toshi/cluster/tn1 hostname:port`
`/service/toshi/cluster/tn2 hostname:port` 

So on so forth, I don't have any particular attachment to this method, but just something to get started with.

**Comment by fhaynes** [comment]
Off the top of my head:

- IP
- Hostname
- Current CPU load (5 min avg or something)
- Free desk space
- iowait
- Node role if we use roles
- Free RAM
