### ISSUE TITLE
Add a modified tantivy-cli

### ISSUE THREAD

**Issue by hntd187** [toshi-search/Toshi#22]
I wanted to add the tantivy-cli into the project binaries as a tool for admins to work with indexes on disk in an easier and more direct way than just through the rest interface. Since tantivy indexes are units by themselves this should be fine.

https://github.com/tantivy-search/tantivy-cli

The CLI doesn't have a license in it @fulmicoton safe to assume it's MIT like tantivy?

**Comment by fulmicoton** [comment]
Yes. Sorry for the omission, I will add that on Monday.
