### ISSUE TITLE
Create module to register with Consul

### ISSUE THREAD

**Issue by fhaynes** [toshi-search/Toshi#24]
When a node comes up, it should try to register with the specified Consul cluster

**Comment by hntd187** [comment]
Which I'd imagine the flow for this is 
1. Look at the lock key in consul
2. If it's not locked, I'm the leader, acquire session lock otherwise, get the details of the master
3. Connect to master, do what needs to be done

**Comment by fhaynes** [comment]
Yup, that's pretty much it.
