### ISSUE TITLE
Bypass WORM arcitechture

### ISSUE THREAD

**Issue by kkonevets** [toshi-search/Toshi#335]
My use case:
I need to update a document on the fly when user modifies it. And the document should become searchable instantly.

My solution: I know Tantivy uses "write once read many" concept and there could be only one writer at once. I guess I can spawn a separate thread with index writer in it and process those docs that need be updated. Though it will block other read threads while committing.

Ideally what I need is the ability to write to index from independent threads each having own writer. Can Toshi do this?

Have any ideas?

**Comment by hntd187** [comment]
No, I don't think it's possible I'm just as contrained by tantivy-search/tantivy#550 as you, but I think we can discuss a solution in that issue.
