### ISSUE TITLE
does toshi have a rust client? if it does,  does it supports submitting bulk request?

### ISSUE THREAD

**Issue by vsop-479** [toshi-search/Toshi#397]
does toshi have a rust client? if it does,  does it supports submitting bulk request?

**Comment by hntd187** [comment]
No, I haven't written a client for toshi yet, but it'd be a matter of taking a lot of the query dsl things and just rolling them into a crate that does the requests for you.

Also yes, Toshi supports bulk indexing right now. I've personally tested this with several gigs of data and it scales pretty well on a single machine. You can find it under handlers/bulk.rs

**Comment by vsop-479** [comment]
@hntd187 hi, I use a httpclient to bulk 100 docs to toshi  every time in one thread，but toshi server always down and can't response anything after bulk some times.  when use 4 threads ,toshi server will down immediatly.  

this is my toshi configuration:
writer_memory = 30000000000
log_level = "info"
json_parsing_threads = 10
bulk_buffer_size = 10000
auto_commit_duration = 120
kind = "log"
min_merge_size = 8
min_layer_size = 10_000
level_log_size = 0.75

doc str length is about 220. so，what‘s the problem of my bulking method？

**Comment by hntd187** [comment]
@vsop-479 can you give me some more details about your request? The schema of your index, how you are making your request? Is toshi throwing any errors in the logs?

**Comment by vsop-479** [comment]
@hntd187 
this is the schema:
[schema.txt](https://github.com/toshi-search/Toshi/files/3507879/schema.txt)

I making my request with a java httpclient, and sending a post request. the entity like this:
[entity.txt](https://github.com/toshi-search/Toshi/files/3507898/entity.txt)

Toshi can handle some bulk requests successfully.
But when it stuck, there is no error. 
It just can't response any request. I have to restart toshi every time.

**Comment by vsop-479** [comment]
@hntd187 sorry, after toshi stuck 3 mins. it throwed errors, and recover back to normal.
[error.txt](https://github.com/toshi-search/Toshi/files/3507965/error.txt)

**Comment by vsop-479** [comment]
@hntd187 sometimes toshi could recover to normal, sometimes it could not.

**Comment by hntd187** [comment]
Hmmm, very odd, I cannot get this bug to show on my local version. Even running these requests over a network they never fail for me. I think you've uncovered something, but I'm not sure how to reproduce this because everything you've given me works fine. 

I made my requests via curl could you try them?

Create the Index
```
curl -X PUT \
  http://localhost:8080/access/_create \
  -H 'Content-Type: application/json' \
  -d '[{"name":"access_time","type":"text","options":{"indexed":false,"stored":true}},{"name":"reply_code","type":"u64","options":{"indexed":false,"stored":true}},{"name":"host_md5","type":"text","options":{"indexed":false,"stored":true}},{"name":"sport","type":"u64","options":{"indexed":false,"stored":true}},{"name":"count","type":"text","options":{"indexed":false,"stored":true}},{"name":"sip","type":"text","options":{"indexed":false,"stored":true}},{"name":"host","type":"text","options":{"indexing":{"record":"position","tokenizer":"default"},"stored":true}},{"name":"serial_num","type":"text","options":{"indexed":false,"stored":true}},{"name":"dns_type","type":"u64","options":{"indexed":true,"stored":true}},{"name":"dport","type":"u64","options":{"indexed":true,"stored":true}},{"name":"dip","type":"text","options":{"indexed":false,"stored":true}}]'
```

Bulk add your documents
```
curl -X POST \
  http://localhost:8080/access/_bulk \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 1182' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:8080' \
  -d '{"access_time":"2019-08-01 16:28:26.508","reply_code":0,"host_md5":"7cb7ba399a499134e212eebb65ef0612","sport":29615,"count":"1;8;6;1","sip":"1.1.1.1","host":"aa.com","serial_num":"QbJK/NOX+","dns_type":1,"dport":63712,"dip":"2.2.2.2"}
{"access_time":"2019-08-01 16:28:26.508","reply_code":0,"host_md5":"7cb7ba399a499134e212eebb65ef0612","sport":29615,"count":"1;8;6;1","sip":"1.1.1.1","host":"aa.com","serial_num":"QbJK/NOX+","dns_type":1,"dport":63712,"dip":"2.2.2.2"}
{"access_time":"2019-08-01 16:28:26.508","reply_code":0,"host_md5":"7cb7ba399a499134e212eebb65ef0612","sport":29615,"count":"1;8;6;1","sip":"1.1.1.1","host":"aa.com","serial_num":"QbJK/NOX+","dns_type":1,"dport":63712,"dip":"2.2.2.2"}
{"access_time":"2019-08-01 16:28:26.508","reply_code":0,"host_md5":"7cb7ba399a499134e212eebb65ef0612","sport":29615,"count":"1;8;6;1","sip":"1.1.1.1","host":"aa.com","serial_num":"QbJK/NOX+","dns_type":1,"dport":63712,"dip":"2.2.2.2"}
{"access_time":"2019-08-01 16:28:26.508","reply_code":0,"host_md5":"7cb7ba399a499134e212eebb65ef0612","sport":29615,"count":"1;8;6;1","sip":"1.1.1.1","host":"aa.com","serial_num":"QbJK/NOX+","dns_type":1,"dport":63712,"dip":"2.2.2.2"}'
```

Check docs in the index
```
curl -X GET \
  http://localhost:8080/access/ \
  -H 'Content-Type: application/json'
```

Also in your config can you set your log level to debug? I have an idea of what might be causing this, but I need to be able to reproduce it. Also ensure if you are using a java client in code that the java client waits around for the response from toshi. On average I was getting responses in under 10ms from the server, but ensure that the client is not sending the request and cutting off before getting a response.

**Comment by vsop-479** [comment]
@hntd187 Yes, the client I am using waits around for the response from toshi.  
I think the stuck I am suffering has same relation to the amount of the documents bulked by the client. Because if the client sends 1000 documents in the bulk request, toshi will stuck immediatly.  When the amount reduced to 100, toshi can responses some requests in under 10ms on average, and 
 stuck after  handled 10 - 15 requests.
I will set the log level to debug to reproduce it tomorrow.

**Comment by hntd187** [comment]
Ahh, I think I know your issue then. Toshi will wait until the documents are processed before returning, the 201 you get. Also, bulk index will always commit at the end, which requires a true index lock in order to execute. Can you tell me a bit more about your flow here? Chances are good Toshi isn't actually stuck here, it's just catching up on the documents it needs to index and probably one bulk indexing completing is taking the index lock holding everything up. 

I think it's probably a good idea here to turn off the automatic commit at the end of the bulk and let the user decide when to commit the index. I think it also makes sense to allow the user to make a request that does nothing but force a commit. I think ES calls it a flush. Do those sound like reasonable changes to you that would work better with how you're using the bulk index?

**Comment by vsop-479** [comment]
@hntd187 Yes, a flush api would be useful when user want to commit the index immediately.  But， Toshi still got stuck when I set auto_commit_duration to 0. This time I made my requests via curl too, but every bulk contains 100 documents.
I sent the request immediately after got the last request's response from toshi.  After I sent about 20 requests, toshi got stuck about 20s, 50s, 100s whether the auto_commit_duration has been set to 120 or 0.  If I use multithreads to send requests, the stuck would become more longer, sometimes may be hours.
I think you can reproduce it in my way.
If bulk index will always commit at the end, I think every bulk request will get its response after take similar time.
What should I do to get a high bulk performance from toshi? 
This is the bulk request I sent:
[bulk_request.txt](https://github.com/toshi-search/Toshi/files/3515402/bulk_request.txt)
This is toshi's configuration:
`host = "localhost"
port = 8021
path = "/data10/toshi"
writer_memory = 3000000000
log_level = "debug"
json_parsing_threads = 10
bulk_buffer_size = 100000
auto_commit_duration = 0|120
experimental = false

[experimental_features]
master = true
nodes = [
    "localhost:8021"
]

[merge_policy]
kind = "log"
min_merge_size = 800000000
min_layer_size = 10_000
level_log_size = 0.75`

**Comment by vsop-479** [comment]
I reproduced it via a shell script:
[bulk.sh.txt](https://github.com/toshi-search/Toshi/files/3518978/bulk.sh.txt)

According to the log, you can see some requests took about 100s to get its response.
[bulk.log.txt](https://github.com/toshi-search/Toshi/files/3518981/bulk.log.txt)

**Comment by hntd187** [comment]
Okay, I think I can work from this and I have an idea about how to fix this lemme work on this a bit. Thank you for being very helpful in understanding this issue @vsop-479

**Comment by hntd187** [comment]
Hey @vsop-479 I have a branch the commit above references if you wanna try it out, I tested it with your input and script and it seems to be running fine locally testing. I wanted to clean it up a bit and merge it.
