### ISSUE TITLE
Hangs..

### ISSUE THREAD

**Issue by kristiandupont** [toshi-search/Toshi#417]
This project looks awesome. I am trying to get it running in the simplest Docker setup possible just to play with it.

My `Dockerfile` looks like this:
```
FROM rust:1.36

WORKDIR /usr/src/myapp

RUN git clone https://github.com/toshi-search/Toshi.git

WORKDIR /usr/src/myapp/Toshi
RUN cargo build

COPY . .

EXPOSE 8080

WORKDIR /usr/src/myapp/Toshi/target/debug

RUN mkdir config
RUN mkdir data
RUN cp -R ../../config.toml ./config

CMD ./toshi
```
The config file is simply copied from the README.

Now, Toshi starts but it seems to hang quite early on:
```
  ______         __   _   ____                 __
 /_  __/__  ___ / /  (_) / __/__ ___ _________/ /
  / / / _ \(_-</ _ \/ / _\ \/ -_) _ `/ __/ __/ _ \
 /_/  \___/___/_//_/_/ /___/\__/\_,_/_/  \__/_//_/
 Such Relevance, Much Index, Many Search, Wow
```
..the `INFO` lines that the README specifies are never printed. Requests aren't handled. What am I doing wrong?

**Comment by hntd187** [comment]
Chances are good it's just changes in toshi since the read me update, do you get a normal response of 
```
{
    "name": "Toshi Search",
    "version": "0.1.1"
}```

If you just do a get on root?

**Comment by hntd187** [comment]
Are you still having this issue? @kristiandupont ?

**Comment by kristiandupont** [comment]
Apologies, you are right, I was actually fighting a proxy configuration. Thank you for responding and for the excellent work!
