### ISSUE TITLE
Register node metadata with Consul

### ISSUE THREAD

**Issue by fhaynes** [toshi-search/Toshi#46]
To start with:

- IP
- Port
- CPU Load
- Data directories
  -  Available space per data directory
- System iowait
- RAM available

These should be reported every N minutes, and could also serve as a heartbeat

**Comment by LucioFranco** [comment]
I think it would be easier to parse and use if you had the disk metrics like this, just like how you have it for directories?

```json
    "disk_metrics": [
        {
            "disk_path": "/dev/sdb"
            "iowait": 0.7,
            "disk_type": "ssd",
            "writes_per_second": 1,
            "reads_per_second": 10,
            "write_latency_ms": 25,
            "read_latency_ms": 3
        },
         {
            "disk_path": "/dev/sdc",
            "iowait": 1.4,
            "disk_type": "ssd",
            "writes_per_second": 1,
            "reads_per_second": 10,
            "write_latency_ms": 25,
            "read_latency_ms": 3
        }
    ]
```

**Comment by fhaynes** [comment]
Yes, this is now outdated. See the PR for the current structure. Closing this.
