### ISSUE TITLE
Is this a drop in replacement that will work pointed from Kibana?

### ISSUE THREAD

**Issue by brandonros** [toshi-search/Toshi#460]
Can I run this on port 9200, point Kibana to it, and have it operate thinking Elasticsearch was present?

**Comment by hntd187** [comment]
No you’d have a bad time doing that. In theory though if you looked at the output from ES mimicking it isn’t hard but i haven’t tried it. It’d be a cool feature down the line to provide default schemas matching various log formats. 

But short answer no it won’t work right away. 
Longer answer yes it could work with some effort.
