### ISSUE TITLE
[Question] Speed Elastic Search vs Toshi

### ISSUE THREAD

**Issue by mysticaltech** [toshi-search/Toshi#469]
Hello, just a question quick question... The Toshi + Tantivy stack are compiled to binary from rust, compared to Elastic Search + Lucene that runs with Java on JVM, the former stack is a lot faster yes? Like performance / resource wise it beats Elastic Search really good huh?

**Comment by hntd187** [comment]
Speaking empirically and this is by no means a complete benchmark so take what I say with a grain of salt, but I've observed searches mostly being about an order of magnitude faster and memory usage being about 1/4 of what the JVM uses in workloads. The memory usage is also much more predictable without a GC and obviously very large indexes do not have issues wiith GC thrash like the JVM would. 

It's very promising results from my own testing and I've done some work to replicate ES's rally tool to work on Toshi, but I'm not anywhere near complete on that or even  to a usable point. And just to be complete, I am taking these observations from running Toshi on a 64core 64gb of memory system, so I am not doing this on a laptop and extrapolating it to what it might run like on a big kid machine.

**Comment by mysticaltech** [comment]
Truly amazing!  Thanks for the explanations. You have indeed a very powerful machine, can't even imagine the size of the workload! Would be great if Toshi could do distributed computing (lots of projects are using something called RAFT these days), I would also love to see it easily deploy on Kubernetes. Don't know if you know about it, a similar interesting project build in golang https://github.com/mosuka/blast.

**Comment by hntd187** [comment]
Thanks for the kind words, raft is coming soon, I have to upgrade to async/await first. I haven't investigated anything with kubernetes yet, but I'm sure I'll get to it.

**Comment by mysticaltech** [comment]
Great to hear this! This kind of open source projects, when done right, can literally change the world.
