### ISSUE TITLE
Best way to add new field ?

### ISSUE THREAD

**Issue by Jonarod** [toshi-search/Toshi#490]
So far I just delete the index folder and generate the index again. My project is still very small so this works, but I believe there should be a better way of RE-indexing documents without deleting the index and RE-importing all data ?

**Comment by hntd187** [comment]
I don't think tantivy supports schema migration at this point so it's not something possible inside tantivy. Conceivably we could manage specific schema versioning. It's a lot of work, but right now your approach is probably the best way.
