### ISSUE TITLE
RangeResult is unused

### ISSUE THREAD

**Issue by fhaynes** [toshi-search/Toshi#50]
```rust
pub struct RangeResult {
    key: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    to: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    from: Option<String>,
    num_docs: u64,
}
```

in RangeResult is throwing an un-used warning during cargo test.

**Comment by hntd187** [comment]
Yes, this will go away when aggregates are in a better spot, it was something I wrote and then never used, so it's safe to ignore it for now.
