### ISSUE TITLE
Syncing or integrating with existing PostgreSQL database

### ISSUE THREAD

**Issue by rrjanbiah** [toshi-search/Toshi#505]
Are there any recommended approach to sync with PostgreSQL? IOW, how do people using Toshi integrate it with their existing PostgreSQL systems?

**Comment by hntd187** [comment]
There isn't anything stopping someone from keeping data in both places as long as the schemas line up, but integration for them would likely be treating them as 2 separate services and depending on what you want from data you go to the appropriate service. Currently there are no sync methods between the two that I am aware of, but I'm open to ideas for future functionality.

**Comment by rrjanbiah** [comment]
@hntd187 Thanks a lot for your comments. Hopefully debezium with Kafka may help
