### ISSUE TITLE
Update to use async/await

### ISSUE THREAD

**Issue by Bondza** [toshi-search/Toshi#507]
I'm not sure how far along you've gotten with async/await, I found the `async-await-beta`-branch where some work was done but it looks like it hasn't been updated for a while. But I decided to play around with the `async-await-beta`-branch, so I updated tokio and hyper to from the alpha versions and managed to get it running. Is there a more up to date branch for async/await?

If you think this could be of any use, [here](https://github.com/Bondza/Toshi/tree/async-await) is my updated branch.

I had issues with `tonic` because it there's only an alpha version of `0.1.0` and that depends on the alpha version of hyper `0.13` and that didn't seem to work with the released version of hyper `0.13`. So I added a `cluster` feature to disable cluster by default.

I ran into another issue as well, when I try to add a the route calling `SearchHandler::all_docs` i get the following error:
```
error[E0277]: `*mut ()` cannot be sent between threads safely
   --> src/router.rs:114:5
    |
114 |     Server::bind(&addr).serve(routes).await?;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `*mut ()` cannot be sent between threads safely
    |
    = help: within `hyper::proto::h2::server::H2Stream<impl core::future::future::Future, hyper::body::body::Body>`, the trait `std::marker::Send` is not implemented for `*mut ()`
    = note: required because it appears within the type `lock_api::GuardNoSend`
    = note: required because it appears within the type `(&index::IndexCatalog, lock_api::GuardNoSend)`
    = note: required because it appears within the type `std::marker::PhantomData<(&index::IndexCatalog, lock_api::GuardNoSend)>`
    = note: required because it appears within the type `lock_api::rwlock::RwLockReadGuard<'_, parking_lot::raw_rwlock::RawRwLock, index::IndexCatalog>`
```
This might be because of https://github.com/Amanieu/parking_lot/issues/197.

**Comment by hntd187** [comment]
Thanks, I'm almost done with async/await switch, but it won't be ready until tonic hits it's stable version, which, to my understanding, depends on tower getting it's async-await release too
