### ISSUE TITLE
would you mind to provide a binary version for different platforms?

### ISSUE THREAD

**Issue by xycloud** [toshi-search/Toshi#513]
its so hard for have a try, would you mind to provide a binary version for different platforms?

**Comment by hntd187** [comment]
? Which platform? Toshi should support windows, linux and osx right away.

**Comment by xycloud** [comment]
macos; please provide one bin; its really hard for me to have a try

**Comment by hntd187** [comment]
Sorry, but at this current time you will have to build the binary yourself via cargo.

**Comment by aadrian** [comment]
@hntd187 Any chance reconsidering this?

GitHub Actions or Travis (and others) are free for open source projects and could build and publish automatically for various platforms.

Thank you.

**Comment by hntd187** [comment]
Sure, I do want to provide this and I haven't been opposed to it. I want to create a normal automated release cycle, but it's something I haven't gotten a chance to do yet, but if someone wants to create a PR to automatically publish built binaries I'd be happy to accept that. I think generally Toshi is in a more stable state and could probably create release packages that would be fine to use, I can't imagine I'll be changing a lot of the forward facing things like that anytime soon.

**Comment by aadrian** [comment]
@hntd187 https://github.com/actions-rs/meta seems more official, and here is also a windows example https://alican.codes/rust-github-actions/

Publishing a release https://github.com/softprops/action-gh-release  (for more than one OS) , or the example of another Rust project https://github.com/urbica/martin/blob/master/.github/workflows/ci.yml#L150
