### ISSUE TITLE
toshi-proto fails to build on macOS Catalina

### ISSUE THREAD

**Issue by drinkitup777** [toshi-search/Toshi#550]
**Describe the bug**
When compiling `toshi`, the compilation process halts at `toshi-proto` with the following error message:

```
 /Toshi/toshi-proto $ cargo build --release                                                                                                       
   Compiling toshi-proto v0.1.0 (/Users/bucko/Toshi/toshi-proto)
error: failed to run custom build command for `toshi-proto v0.1.0 (/Users/bucko/Toshi/toshi-proto)`

Caused by:
  process didn't exit successfully: `/Users/bucko/Toshi/target/release/build/toshi-proto-879e8b6972e136dd/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0:        0x107bcbf25 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb58f5347bb1ea7b9
   1:        0x107bed9f1 - core::fmt::write::ha9abb3322774bd4f
   2:        0x107bdbe39 - std::io::Write::write_fmt::h72ef3cad46ef5da7
   3:        0x107bcdb43 - std::panicking::default_hook::{{closure}}::hb0f024d11ad4eda7
   4:        0x107bcd86f - std::panicking::default_hook::h8f36dfbe4fa71efd
   5:        0x107bce27c - std::panicking::rust_panic_with_hook::h19f1d0cf9bc48900
   6:        0x107bcdd39 - std::panicking::continue_panic_fmt::ha03dadffb484b681
   7:        0x107bcdc89 - rust_begin_unwind
   8:        0x107bf5b9c - core::panicking::panic_fmt::hf2ccf250d7b43fe7
   9:        0x107bf59a9 - core::result::unwrap_failed::h4d74b9130c1d473e
  10:        0x107ae7971 - tonic_build::fmt::hcc47c796d443ae31
  11:        0x107aba0fd - build_script_build::main::hc8f0475db060ef8d
  12:        0x107a9f11b - std::rt::lang_start::{{closure}}::h27ced1c1e74dca7f
  13:        0x107bcdc68 - std::panicking::try::do_call::he4301933c114d277
  14:        0x107bdde1f - __rust_maybe_catch_panic
  15:        0x107bcac63 - std::rt::lang_start_internal::h93184985107106ec
  16:        0x107abbd79 - main
```

**To Reproduce**
1. On macOS Catalina 10.15.1, run `git clone https://github.com/toshi-search/Toshi.git`
2. `cd Toshi`
3. `export RUST_BACKTRACE=full`
4. `cargo build --release`
5. See error (copied & pasted above)

**Expected behavior**
Toshi compiles successfully

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.1
 - Rust Version: 1.41.0

**Comment by hntd187** [comment]
Hmmm, interesting,  thanks for the reproduce. I'll look into this

**Comment by hntd187** [comment]
Stupid question here, do you have the osx clang build tools installed?

**Comment by drinkitup777** [comment]
Do you mean the `clang` executable from Xcode command line tools? It's installed:

> \> clang --version
> Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by hntd187** [comment]
I am not sure what is happening here for you, a cold build on my mac works fine, I asked several other people I knew to try it as well and it all worked fine for them. So I cannot reproduce this .

**Comment by andrewbanchich** [comment]
I'm also experiencing this on Catalina. Neither `master` nor `async-await` are building for me.

**Comment by hntd187** [comment]
Interesting the errors @andrewbanchich is seeing I have also gotten on Windows so I do not think that is specific to OSX. Can you guys list your rustc versions? Mine builds fine on mojave which I noticed might be an older version of rust so maybe it’s a regression there?

**Comment by tehroot** [comment]
Builds successfully for me on Catalina with 1.42 Nightly and 1.43 Nightly, I switched back to 1.41 Stable and it also builds for me successfully on Catalina. 

I have the latest commandlinetools and clang version.

**Comment by andrewbanchich** [comment]
I'll check the rustc version later today (those were from my home computer).

I just tried pulling and compiling on my work computer (Ubuntu 18.04) and it's giving me the same errors.

Here is that info for my Ubuntu machine:

```
~/D/Toshi (master|✔) [101] $ rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
```

```
~/D/Toshi (master|✔) $ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Just to confirm I'm not missing anything, I'm cloning the repo, `cd ./Toshi`, then `cargo install --path .`

**Comment by andrewbanchich** [comment]
> I would suggest making sure you're using the latest stable version, or trying to build against the latest nightly.

@tehroot Even after `rustup override set nightly` I'm getting the same errors on Ubuntu 18.04.

**Comment by hntd187** [comment]
@andrewbanchich are you running `cargo install` or `cargo build`? I don't think `cargo install` is correct.

**Comment by hntd187** [comment]
Also @andrewbanchich can you try and build the `raft` branch and see if that works? I am working currently on this branch.

**Comment by andrewbanchich** [comment]
@hntd187 I was running `cargo install`, which I always thought was just an alias for `cargo build --release && mv ~/.cargo/bin`. However, `cargo build --release` is working for me on Catalina now, so that explains it. Thanks!

`raft` also compiles for me with `cargo build --release`.
