### ISSUE TITLE
Error when deserializing in the toshi-client examples

### ISSUE THREAD

**Issue by goodsauce** [toshi-search/Toshi#559]
**Describe the bug**
Using the `toshi-client` as in the examples seems to conflict with the `toshi-server` output format, specifically where the `toshi-server` wraps its document properties in square brackets.
```json
"doc":{ 
  "rating":[ 10 ],
  "title":[ "title" ]
}
```

**To Reproduce**
Just a slight adaption of the example curl requests
```bash
curl -X PUT \
  http://localhost:8080/wiki/_create \
  -H 'Content-Type: application/json' \
  -d '[
    {
      "name": "title",
      "type": "text",
      "options": {
        "indexing": {
          "record": "position",
          "tokenizer": "default"
        },
        "stored": true
      }
    },
    {
      "name": "rating",
      "type": "i64",
      "options": {
        "indexed": true,
        "stored": true
      }
    }
  ]'

curl -X PUT \
  http://localhost:8080/wiki \
  -H 'Content-Type: application/json' \
  -d '{
        "options": { "commit": true },
        "document": {
          "title": "title",
          "rating": 10
        }
    }'
```
Then running a slight adaption of `examples/exact_query.rs`
```rust
#[derive(Clone, Deserialize)]
pub struct Wiki {
    title: String,
    rating: i32,
}

pub fn main() -> Result<()> {
    let c = ToshiClient::new("http://localhost:8080")?;
    let query = Query::Exact(ExactTerm::with_term("title", "title"));
    let search = Search::with_query(query);
    let docs: SearchResults<Wiki> = c.search("wiki", search)?;

    Ok(())
}
```
**Results in this error**
```
Error: JsonError(Error("invalid type: sequence, expected i32", line: 1, column: 55))
```
Running
```bash
curl -X GET http://localhost:8080/wiki -H 'Content-Type: application/json'
```
Outputs
```json
{ 
   "hits":1,
   "docs":[ 
      { 
         "score":1.0,
         "doc":{ 
            "rating":[ 10 ],
            "title":[ "title" ]
         }
      }
   ],
   "facets":[]
}
```
*Note the brackets around `"rating":[ 10 ]` and `"title":[ "title" ]`*
Changing our rust struct to
```rust
#[derive(Clone, Deserialize)]
pub struct Wiki {
    title: [String; 1],
    rating: [i32; 1],
}
```
Seems to work, but i'm sure that is not the intention of this library. 
I'm not sure if there the square brackets were intentional for some other reason, but if the solution is to simply remove them, I'm willing to attempt a pull request

**Comment by hntd187** [comment]
Apologies for a slow response here. The arrays you see there are side effects of tantivy's internal document struct which is `BTreeMap<String, Vec<Value>>` so we'd need a custom deserializer to look at the type here of the value and do the right thing on flattening that Vec. It's just one of the many things I haven't gotten a chance to tackle yet, but if you are up to it it should be fairly straight forward.

**Comment by goodsauce** [comment]
All good
So to clarify, a custom impl of `serde::Deserialize` is needed which would require a custom procedural-macro for it to work on any user / consumer defined struct?

**Comment by hntd187** [comment]
Hey @goodsauce I had some time on a flight, so I updated the result serializing and removed the extra layer of vecs in #565 . It's kind of a bug but not really. Either way, returned results should be flat now.

**Comment by goodsauce** [comment]
Tested and working, thanks!
Actually glad the change was done in the server :)
