### ISSUE TITLE
Add Shard creation

### ISSUE THREAD

**Issue by fhaynes** [toshi-search/Toshi#56]
There should be a function that creates a Shard (either primary or replica), the underlying tantivy index, and registers it in Consul

**Comment by LucioFranco** [comment]
@fhaynes do you mind explaining a bit what your strategy is for this? Mostly just curious.

**Comment by fhaynes** [comment]
Whenever a node receives a request to create an index, the following should happen:

1. Determine number of needed primary shards. This is either specified in the index creation request, or the default is used.
2. Determine the number of replicas for each primary shard needed. This is either specified in the index creation request or the default is used.
3. Nodes are chosen for each primary and each replica, with the minimal following rules:
  - If possible, each Primary should be on a different node. If that is not possible, they should be distributed across physical devices on the node.
  - If possible, each replica should be on a distinct node. 
  - A replica should never be on the same node as its primary unless there is no other choice
4. The node that received the index creation request makes an RPC call to all of the chosen nodes to create the shards. 
5. These shards register in Consul under the index. The metadata will include what node they are located on.
6. Whenever a write comes in, the node looks up the primary shards for the index and chooses to send the write to.
7. The data is sent to the chosen Primary and written to disk
8. The Primary node then writes the data out to all the Replicas
9. Once this is all done, a 201 is returned to the client
10. Optionally, a request can specify that it doesn't want to wait for a response, or it only wants to wait for a Primary to have written it.
11. The heuristics for choosing where to place Shards will be based primarily on current node disk i/o, CPU, RAM usage, etc
