### ISSUE TITLE
build error: could not compile `bitpacking` 

### ISSUE THREAD

**Issue by Temkit** [toshi-search/Toshi#561]
**Describe the bug**
error: could not compile `bitpacking`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name bitpacking /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/bitpacking-0.8.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C codegen-units=1 --cfg 'feature="bitpacker4x"' -C metadata=87ad2b421276f3c7 -C extra-filename=-87ad2b421276f3c7 --out-dir /home/ec2-user/Toshi/target/release/deps -L dependency=/home/ec2-user/Toshi/target/release/deps --extern crunchy=/home/ec2-user/Toshi/target/release/deps/libcrunchy-88fb3ac03638e579.rmeta --cap-lints allow` (signal: 9, SIGKILL: kill)
**To Reproduce**
cargo build --release

**Desktop (please complete the following information):**
 - OS: Mac Os Catalina

**Comment by hntd187** [comment]
This is probably a dup if #550
