### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cooperspencer** [toshi-search/Toshi#566]
Could you create some documentation like in the wiki?
It would be nice if there were things documented like how to delete an index or how to bulk documents. Just a little bit like the documentation of Elasticsearch.

PS: You've created an awesome piece of software so far 👍

**Comment by hntd187** [comment]
Toshi is still fairly experimental and changing a lot in it's interface so adding thorough documentation would be just another thing to fall behind on right now until I am at a point where I want to say the API will remain consistent for the future. In the meantime to answer your questions 

1. There is no current way to delete an index, it's new functionality I haven't gotten a chance to implement yet
2. The best way to see the bulk insert work is probably from it's tests

Again, what is in the readme is mostly meant to get people started (even though it's also probably out of date) everything in my opinion is close to calming down on the high churn so it's something getting closer as I get through things

**Comment by cooperspencer** [comment]
Thanks for the answer. I will checkout the tests and see what can be done so far.
