### ISSUE TITLE
Couldn't create the index file

### ISSUE THREAD

**Issue by mjl4043** [toshi-search/Toshi#599]
I am new to this, wanted your help. When i run the script for creating the index file, an error is thrown.

{"message":"IO Error: expected value at line 1 column 1"}curl: (6) Could not resolve host: application. 

How do i resolve this?

**Comment by hntd187** [comment]
Can you show me the curl command you are trying to run please?

**Comment by mjl4043** [comment]
The same code as given on your github profile for uploading documents to
index. But it is showing me the error given below.

error:1408F10B:SSL routines:ssl3_get_record:wrong version number
