### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by mjl4043** [toshi-search/Toshi#603]
Hi. I am trying to run this on ubuntu.
The build command gives the following error-

error: failed to run custom build command for `toshi-proto v0.1.0 (/home/ubuntu/Toshi/toshi-proto)`

Caused by:
  process didn't exit successfully: `/home/ubuntu/Toshi/target/release/build/toshi-proto-d68a507dc1a704df/build-script-build` (exit code: 1)
--- stderr
error running rustfmt: Os { code: 2, kind: NotFound, message: "No such file or directory" }

How can it be rectified? Thank you.

**Comment by hntd187** [comment]
Is rust fmt installed with cargo?

**Comment by mjl4043** [comment]
Sorry i had rust instead of rustup.

Issue solved

**Comment by mjl4043** [comment]
While compiling toshi-server it is showing the following issue:

Compiling toshi-server v0.1.1 (/home/ubuntu/Toshi/toshi-server)
error: could not compile `toshi-server`.

Caused by:
  process didn't exit successfully: `rustc --crate-name toshi_raft --edition=2018 toshi-server/src/bin/toshi_raft.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C codegen-units=1 -C metadata=bf7ba9a997e7ee1f -C extra-filename=-bf7ba9a997e7ee1f --out-dir /home/ubuntu/Toshi/target/release/deps -L dependency=/home/ubuntu/Toshi/target/release/deps --extern anyhow=/home/ubuntu/Toshi/target/release/deps/libanyhow-54c43014534ff3e1.rlib --extern async_trait=/home/ubuntu/Toshi/target/release/deps/libasync_trait-049e3ce8073dba8f.so --extern bytes=/home/ubuntu/Toshi/target/release/deps/libbytes-5e0c4bb21dc9a673.rlib --extern clap=/home/ubuntu/Toshi/target/release/deps/libclap-99f935a8d1468c93.rlib --extern config=/home/ubuntu/Toshi/target/release/deps/libconfig-1eb7e78efc51cc52.rlib --extern crossbeam=/home/ubuntu/Toshi/target/release/deps/libcrossbeam-2634ad7abc29a042.rlib --extern dashmap=/home/ubuntu/Toshi/target/release/deps/libdashmap-af201934e7ec5af7.rlib --extern futures=/home/ubuntu/Toshi/target/release/deps/libfutures-bc921e3e9bc33b6f.rlib --extern http=/home/ubuntu/Toshi/target/release/deps/libhttp-f8fed886f4a6a781.rlib --extern hyper=/home/ubuntu/Toshi/target/release/deps/libhyper-043077be4983b189.rlib --extern log=/home/ubuntu/Toshi/target/release/deps/liblog-749e53be6ab524b6.rlib --extern raft=/home/ubuntu/Toshi/target/release/deps/libraft-c46ef07a68200934.rlib --extern rand=/home/ubuntu/Toshi/target/release/deps/librand-ee63ff5985799f14.rlib --extern serde=/home/ubuntu/Toshi/target/release/deps/libserde-64931822abb14ef9.rlib --extern serde_json=/home/ubuntu/Toshi/target/release/deps/libserde_json-6963a3273c7ac5b5.rlib --extern serde_urlencoded=/home/ubuntu/Toshi/target/release/deps/libserde_urlencoded-e57eadc0c695993c.rlib --extern slog=/home/ubuntu/Toshi/target/release/deps/libslog-b23f0856d90117a6.rlib --extern slog_async=/home/ubuntu/Toshi/target/release/deps/libslog_async-252d253a63346b49.rlib --extern slog_scope=/home/ubuntu/Toshi/target/release/deps/libslog_scope-97b640ef68ce31fa.rlib --extern slog_stdlog=/home/ubuntu/Toshi/target/release/deps/libslog_stdlog-0c209398404087bc.rlib --extern slog_term=/home/ubuntu/Toshi/target/release/deps/libslog_term-bff5c29c2889058b.rlib --extern sloggers=/home/ubuntu/Toshi/target/release/deps/libsloggers-8d76be2d6d8899d0.rlib --extern structopt=/home/ubuntu/Toshi/target/release/deps/libstructopt-3e1cee713268d365.rlib --extern tantivy=/home/ubuntu/Toshi/target/release/deps/libtantivy-fd29e8219e50dcfe.rlib --extern thiserror=/home/ubuntu/Toshi/target/release/deps/libthiserror-2e0570c85cc89de7.rlib --extern tokio=/home/ubuntu/Toshi/target/release/deps/libtokio-080e854d6e2f363e.rlib --extern toml=/home/ubuntu/Toshi/target/release/deps/libtoml-f226b592ec611b72.rlib --extern tonic=/home/ubuntu/Toshi/target/release/deps/libtonic-f7a25e1eaa1c5678.rlib --extern toshi_proto=/home/ubuntu/Toshi/target/release/deps/libtoshi_proto-b10e5e150e7d20b6.rlib --extern toshi_raft=/home/ubuntu/Toshi/target/release/deps/libtoshi_raft-be84944768a3433c.rlib --extern toshi_server=/home/ubuntu/Toshi/target/release/deps/libtoshi_server-e3b5593d2e98166c.rlib --extern toshi_types=/home/ubuntu/Toshi/target/release/deps/libtoshi_types-b15d4c0b64aa06bc.rlib --extern tower_util=/home/ubuntu/Toshi/target/release/deps/libtower_util-a8fc1ffee1b63ae3.rlib --extern uuid=/home/ubuntu/Toshi/target/release/deps/libuuid-c8e0431d8c2a4940.rlib -L native=/home/ubuntu/Toshi/target/release/build/backtrace-sys-dadb7e0b8ed0a587/out -L native=/home/ubuntu/Toshi/target/release/build/zstd-sys-8efd0166da9faeeb/out` (signal: 9, SIGKILL: kill)

**Comment by hntd187** [comment]
are you not using cargo? the sig killl implies you are killing the build yourself?

**Comment by mjl4043** [comment]
Yes i ran the command cargo build --release.
