### ISSUE TITLE
Unable to build on FreeBSD/ HardenedBSD

### ISSUE THREAD

**Issue by dmilith** [toshi-search/Toshi#629]
**Describe the bug**
zsh: segmentation fault  cargo build --release

**To Reproduce**
git clone repo; cd repo; cargo build

**Expected behavior**
Normal build?

**Desktop (please complete the following information):**
 - OS: FreeBSD 12.1
 - Rust Version: 1.43.1
 - Version: master

**Comment by hntd187** [comment]
Segmentation fault? Do other rust binaries build fine?
