### ISSUE TITLE
Cargo build  error with error type :expected struct `std::io::Error`, found struct `std::string::String`

### ISSUE THREAD

**Issue by stanxii** [toshi-search/Toshi#686]
**Describe the bug**
When cargo build ,show a compile error.

**To Reproduce**
❯ cargo build --release     
then show error
   Compiling toshi-server v0.1.1 (/home/xiyx/free/Toshi/toshi-server)
error[E0308]: mismatched types
  --> toshi-server/src/lib.rs:40:52
   |
40 |         .map_err(|err| toshi_types::Error::IOError(err.to_string()))
   |                                                    ^^^^^^^^^^^^^^^ expected struct `std::io::Error`, found struct `std::string::String`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `toshi-server`.

To learn more, run the command again with --verbose.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 LTS
 - Rust Version: rustc 1.46.0 (04488afe3 2020-08-24)
 - Version master branch

**Additional context**

**Comment by hntd187** [comment]
Thanks for reporting this bug, I fixed it.
