### ISSUE TITLE
toshi panic at run time due to tokio

### ISSUE THREAD

**Issue by abdelmonem17** [toshi-search/Toshi#745]
The following exception threw at run time when running toshi in latest update

thread 'tokio-runtime-worker' panicked at 'assertion failed: now >= lock.elapsed', /home/my-user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/time/driver/mod.rs:260:9

**Comment by hntd187** [comment]
Can you give some details about what you were doing at the time of this panic?

**Comment by abdelmonem17** [comment]
@hntd187  I only compiled toshi in this version and ran it and after few seconds always gives me this error but the program still running and responds to requests 
this behavior exists in this version and the pervious one undex linux OS but under windows do well

**Comment by hntd187** [comment]
Can you turn on the full backtrace and run again?

**Comment by abdelmonem17** [comment]
@hntd187  thank you for you interest, I managed to determine the problem, it was as issue in rust that fails to detect the virtual machine which I worked in , the details here : @https://github.com/tokio-rs/tokio/issues/3619

**Comment by hntd187** [comment]
Thanks for following up, appreciate it
