### ISSUE TITLE
Support for dynamic fields?

### ISSUE THREAD

**Issue by mkalus** [toshi-search/Toshi#768]
One of Solr's killer features is dynamic fields (e.g. `*_t`for text fields). You simply post a field called description_t and it becomes a text field as defined by your schema. Are there plans to include something like this into Toshi?

One of my larger projects is working with dynamic fields: Admins can define their own additional fields that are stored in the index - they can also search those fields specifically, so I cannot just dump them into one catch-all index field. I think such a feature in Toshi would be tremendously helpful for such use cases where you do not know the schema in advance.

**Comment by hntd187** [comment]
Probably better to ask the underlying search library https://github.com/tantivy-search/tantivy this question, if tantivy has support for this then we can look into supporting it.

**Comment by mkalus** [comment]
Thanks for the quick answer. Having just looked into their code examples, I realized that tantivy defines the schema not Toshi. I have worked a lot with Lucene, Solr and a bit with Elastic Search and Lucene does not enforce schemas. This makes it easy for search servers to create indexes on the fly...
