### ISSUE TITLE
cargo build --release failed

### ISSUE THREAD

**Issue by jimmy980189** [toshi-search/Toshi#801]
Currently I just followed the instructions (which means I just clone and `cargo build --release` the repo)
But I came into this error 
![image](https://user-images.githubusercontent.com/45072996/123790679-301fe480-d911-11eb-9fdf-07b0b48d26bd.png)
I found out that maybe it is caused by missing `list.rs` in the `toshi-server/src/handlers`
which  is new added to master branch 
![image](https://user-images.githubusercontent.com/45072996/123791044-93117b80-d911-11eb-94f2-ce6dbf1762d7.png)

**Comment by hntd187** [comment]
Thanks, I am not smart, I forgot to check this file in.

**Comment by hntd187** [comment]
This should be fixed let me know if it still happens.
